### ISSUE TITLE
Compile the aosp n problem

### ISSUE THREAD

**Issue by qiurigao** [MediatekAndroidDevelopers/android_device_jiayu_s3plus_n560a#4]
Hi,: I'm glad you can release the source code. I try to compile, but encounter problems as follows.
Once I compile other phone does not have, can you help me to solve? Thank you very much

ninja: error: 'out/target/product/s3plus_n560a/kernel', needed by 'out/target/product/s3plus_n560a/boot.img', missing and no known rule to make it
build/core/ninja.mk:84: recipe for target 'ninja_wrapper' failed

**Comment by qiurigao** [comment]
Initially compiled more than ten minutes to appear this mistake, I am a mystery

**Comment by dragonpt** [comment]
This is simply a device tree

You are talking about compiling a whole ROM, it's completely unrelated to this github repo.
You need to fetch our kernel, and do proper work for a whole ROM to compile and boot.

Again  the issue is unrelated to this repo
Bb
